### ISSUE TITLE
Leave/change squad

### ISSUE THREAD

**Issue by VaniaMi** [shuki25/edscc#11]
**Is your feature request related to a problem? Please describe.**
Issue: I can't leave the squadron which I mistakenly chose during registration.

**Describe the solution you'd like**
Add the ability to leave/change squad.

**Describe alternatives you've considered**
no ideas :с

**Additional context**
If you have the opportunity to delete the current squadron on my account, I can provide the necessary info.

Thank you

**Comment by shuki25** [comment]
Let me know your commander's name and I'll manually reset it in the database so that you can join the right squadron. I plan to add the ability to switch squadron soon so everyone can do so whenever they want.

**Comment by VaniaMi** [comment]
> Let me know your commander's name and I'll manually reset it in the database so that you can join the right squadron. I plan to add the ability to switch squadron soon so everyone can it do so whenever they want.

Thanks for the quick response, my commander name is Captain Vrungel.

**Comment by shuki25** [comment]
Ok, I have reset your squadron setting.  Please log back in, you should be able to choose your squadron.

**Comment by shuki25** [comment]
Now can leave or change squadron.
