### ISSUE TITLE
Unable to link to Squadron

### ISSUE THREAD

**Issue by NKDavis** [shuki25/edscc#39]
**Describe the bug**
I have been accepted as a member of the Paladin Consortium Squadron.
Other members can see me in the squadron roster.
When I log in I get directed to a page which says"Pending Access" and directs me back to the log in screen.

Most frustrating!
**To Reproduce**
1. Login and apply to join a squadron
2. Be accepted into the squadron
3. Discover that EDSCC thinks you are still awaiting approval.

**Expected behavior**
The ability to log in to my squadron

**Screenshots**
![image](https://user-images.githubusercontent.com/19611905/54864123-e374f880-4d5a-11e9-9fe5-d918763ff15e.png)

![image](https://user-images.githubusercontent.com/19611905/54864131-16b78780-4d5b-11e9-9c6d-38e2e89f6177.png)

![image](https://user-images.githubusercontent.com/19611905/54864137-35b61980-4d5b-11e9-8739-b1abff57d16e.png)

**Desktop (please complete the following information):**
 - OS: MS Windows 10
 - Browser Chrome
 - Version 72.0.3626.121

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuki25** [comment]
Are you still having this problem? The database says you have been granted access to the squadron.

**Comment by NKDavis** [comment]
Hi,
 
Problem solved thanks. 
 
It was my misunderstanding. I had not yet been accepted by the Squadron Leader but, because my status showed as joined, I thought the acceptance had been granted.
 
My apologies for wasting your time.
 
Thanks,
 
Neil.

**Comment by shuki25** [comment]
Closing this issue.  Thank you for the update.
