### ISSUE TITLE
Ability to unlock Squadron Leader as Himself

### ISSUE THREAD

**Issue by BlackJack1979** [shuki25/edscc#43]
Cant Log in after Locking myself as Squadron Leader...

**Comment by shuki25** [comment]
Locked yourself out by accident? Just unlocked your account. I will add a check to make sure the squadron owner is never get banned or the like.

**Comment by BlackJack1979** [comment]
Yeah it was an Accident, I was to Tired. :) Thank You for your super fast Help!

**Comment by shuki25** [comment]
Added mechanism to prevent anyone changing squadron owner status.  It will always be marked as "Approved".
