### ISSUE TITLE
Password change function doesn't work if user signed up with blank password

### ISSUE THREAD

**Issue by chrisdg3** [shuki25/edscc#46]
**Describe the bug**
Password change function doesn't work if user signed up with blank password

**To Reproduce**
1. Sign up with filled out password but neglect to click to agree to terms
2. Click to agree but don't notice password fields have been blanked
3. Account is now setup with blank password
4. Button to confirm password change cannot be clicked while the old password field is blank and putting a dummy password in the field results in failure

**Expected behavior**
Either account creation should fail with a blank password or the password change should work with a blank old password

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox
 - Version 66.0.2 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuki25** [comment]
Thank you for the report.  Will address this and fix the bug.  In the meantime, you can log out and click on Forgot Password, there you should be able to change your password without the current password.

**Comment by shuki25** [comment]
Bug fixed.
