### ISSUE TITLE
Email notification of new login location

### ISSUE THREAD

**Issue by shuki25** [shuki25/edscc#47]
**Is your feature request related to a problem? Please describe.**
Would be nice to get an email alert if I'm logging in the account from a different location.

**Describe the solution you'd like**
An email sent to me if I am logged into another location.

**Comment by Atomicbeast101** [comment]
May be nice to also have 2FA as well. Can enforce it only once if accessing in a different place, otherwise it'll get annoying with doing the 2FA each time in the same place.

Just a suggestion.
