### ISSUE TITLE
It's possible to remove squadron gaming platform

### ISSUE THREAD

**Issue by slubman** [shuki25/edscc#54]
**Describe the bug**
From the squadron settings page it's possible to choose the « empty » option for the squadron platform.

**To Reproduce**
1. Go to 'Squadron settings > Gaming platform'
2. Choose the empty option
3. Save changes

**Expected behavior**
An error when trying to save with an empty value in this field.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 66

**Additional context**
By the look of it, having a squadron with such a settings break the page where a new member is asked to choose a squadron.

**Comment by shuki25** [comment]
I was able to save the changes when choosing blank for gaming platform and didn't get the error. Was it during creating a new squadron or changing from a platform to blank in the squadron settings page?

Regardless, the intended behavior should not show a blank option.  Will look at the code and fix it. Thanks for the heads up.

**Comment by slubman** [comment]
I changed it on an already existing account.

The error is not visible from the account that made the change to the squadron, but for a new SDCC account trying to access the site at the same time after mail validation, when the user should be asked to choose a squadron to join.

**Comment by shuki25** [comment]
Ok. I'm trying to decide if we should have separate squadron entity for each platform or should we combine them all in one and use the tags to indicate which platforms this particular squadron supports? It now supports downloading journal files for Xbox and PS4 so it doesn't matter anymore, combining them all works.  I just have to remove that extra field from the code base and the database. AFAIK, It would require a considerable change in the code base to remove one field.

**Comment by slubman** [comment]
Actually, we have a squadron with the same name and tag, and almost the same roles, on all platforms.
But IMHO, it's a good idea to have them under one roof on EDSCC.
Actually even if EDSCC does not reflect the multi-platform aspect, it's already possible to have members from different platforms in the same squadron :-)

**Comment by shuki25** [comment]
I agree. I will move it to squadron tags instead so that different platforms can be under one roof.
