### ISSUE TITLE
Accidentally had an error in email, now I can't use my Commander Name.

### ISSUE THREAD

**Issue by KyleWolverine** [shuki25/edscc#77]
I entered my email incorrectly, forgetting a letter on accident. Now when I go to register with the right email, I cannot use my Commander Name from in game. How can I fix this?

Incorrect:   kylebail@umich.du
Correct:     kylebail@umich.edu
CMDR Name: Kyle_Wolverine

**Comment by shuki25** [comment]
Updated your email in the system.  Have it resend you the activation code, it should go to the correct email address now.
