### ISSUE TITLE
Associate ExplorationData with StationFaction

### ISSUE THREAD

**Issue by Alphaloft** [shuki25/edscc#9]
**Is your feature request related to a problem? Please describe.**
ExplorationData in Player Activities Report shows no faction association. 

**Describe the solution you'd like**
In the PMF cell of the reports table, show either StationFaction or SystemFaction from the journal, whichever benefits from exploration data (to be determined).

**Describe alternatives you've considered**
Since the SellExplorationData event does not include faction beneficiary, inference must be made from nearby events, particularly previous FSDJump or Docked event. If this is not possible, leave as is. (I have no alternative suggestion.)

**Additional context**
Found in FSDJump event:
`"SystemFaction":{ "Name":"Garuda Ved", "FactionState":"Expansion"`

Found in Docked event:
`{ "timestamp":"2019-03-08T05:58:10Z", "event":"Docked", "StationName":"Elcano Landing", "StationType":"CraterOutpost", "StarSystem":"Capricorni Sector EG-Y d72", "SystemAddress":2484361726323, "MarketID":3502624768, "StationFaction":{ "Name":"Garuda Ved", "FactionState":"Expansion" }`

**Comment by Alphaloft** [comment]
From what I have heard, StationFaction reaps the rewards from SellExplorationData. So the Dock event would be needed as opposed to FSDJump.

**Comment by shuki25** [comment]
Ok great, I'll implement it that way then.  Which faction would get the rewards?  The controlling faction?  Like in your example in the post, `"StationFaction":{ "Name":"Garuda Ved", "FactionState":"Expansion" }`?

**Comment by Alphaloft** [comment]
Yes, the controlling faction of the station is who benefits from selling the exploration data.
